export const CHANGE_INPUT_REG_LAST_NAME = 'CHANGE_INPUT'
export const CHANGE_INPUT_REG_NAME = 'CHANGE_INPUT'
export const CHANGE_INPUT_REG_NICKNAME = 'CHANGE_INPUT'
export const CHANGE_INPUT_REG_PASSWORD = 'CHANGE_INPUT'
export const CHANGE_INPUT_REG_PASSWORD2 = 'CHANGE_INPUT'

export const VERIFIED_REGISTRATION = 'VERIFIED_REGISTRATION'