export const CHANGE_INPUT_REG_LAST_NAME = 'CHANGE_INPUT'
export const CHANGE_INPUT_REG_NAME = 'CHANGE_INPUT'
export const CHANGE_INPUT_REG_NICKNAME = 'CHANGE_INPUT'
export const CHANGE_INPUT_REG_PASSWORD = 'CHANGE_INPUT'
export const CHANGE_INPUT_REG_PASSWORD2 = 'CHANGE_INPUT'

export const VERIFIED_REGISTRATION = 'VERIFIED_REGISTRATION'
export const ERROR_LAST_NAME = 'ERROR_LAST_NAME'
export const ERROR_LAST_NAME_OFF = 'ERROR_LAST_NAME_OFF'
export const ERROR_NAME = 'ERROR_NAME'
export const ERROR_NAME_OFF = 'ERROR_NAME_OFF'
export const ERROR_NICKNAME = 'ERROR_NICKNAME'
export const ERROR_NICKNAME_TEXT = 'ERROR_NICKNAME_TEXT'
export const ERROR_NICKNAME_OFF = 'ERROR_NICKNAME_OFF'

export const NICKNAME_REGISTRATED = 'NICKNAME_REGISTRATED'

export const SIMILAR_PASSWORD = 'SIMILAR_PASSWORD'
export const LESS_THAN_8 = 'LESS_THAN_8'

export const PASSWORD_OFF = 'PASSWORD_OFF'

export const TOKEN = 'TOKEN'

export const NICKNAME = 'NICKNAME'